apiVersion: v1
kind: Service
metadata:
  name: {{ include "g2-grafana.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "g2-grafana.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}
