apiVersion: v1
kind: Service
metadata:
  name: {{ include "g2-prometheus.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9090
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "g2-prometheus.name" . }}
